// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package enhanced

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type KmeshTracepointBpfSock struct {
	BoundDevIf     uint32
	Family         uint32
	Type           uint32
	Protocol       uint32
	Mark           uint32
	Priority       uint32
	SrcIp4         uint32
	SrcIp6         [4]uint32
	SrcPort        uint32
	DstPort        uint16
	_              [2]byte
	DstIp4         uint32
	DstIp6         [4]uint32
	State          uint32
	RxQueueMapping int32
}

type KmeshTracepointBpfSockTuple struct {
	Ipv4 struct {
		Saddr uint32
		Daddr uint32
		Sport uint16
		Dport uint16
	}
	_ [24]byte
}

type KmeshTracepointBuf struct{ Data [40]int8 }

type KmeshTracepointManagerKey struct {
	NetnsCookie uint64
	_           [8]byte
}

type KmeshTracepointSockStorageData struct {
	ConnectNs      uint64
	Direction      uint8
	ConnectSuccess uint8
	_              [2]byte
	PidTgid        uint32
	DstSvcName     [192]int8
}

// LoadKmeshTracepoint returns the embedded CollectionSpec for KmeshTracepoint.
func LoadKmeshTracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KmeshTracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load KmeshTracepoint: %w", err)
	}

	return spec, err
}

// LoadKmeshTracepointObjects loads KmeshTracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KmeshTracepointObjects
//	*KmeshTracepointPrograms
//	*KmeshTracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKmeshTracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKmeshTracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KmeshTracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTracepointSpecs struct {
	KmeshTracepointProgramSpecs
	KmeshTracepointMapSpecs
	KmeshTracepointVariableSpecs
}

// KmeshTracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTracepointProgramSpecs struct {
	SendmsgEntry *ebpf.ProgramSpec `ebpf:"sendmsg_entry"`
}

// KmeshTracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTracepointMapSpecs struct {
	KmLogEvent     *ebpf.MapSpec `ebpf:"km_log_event"`
	KmManage       *ebpf.MapSpec `ebpf:"km_manage"`
	KmOrigDst      *ebpf.MapSpec `ebpf:"km_orig_dst"`
	KmPidDst       *ebpf.MapSpec `ebpf:"km_pid_dst"`
	KmSockstorage  *ebpf.MapSpec `ebpf:"km_sockstorage"`
	KmTmpbuf       *ebpf.MapSpec `ebpf:"km_tmpbuf"`
	KmeshMap1600   *ebpf.MapSpec `ebpf:"kmesh_map1600"`
	KmeshMap192    *ebpf.MapSpec `ebpf:"kmesh_map192"`
	KmeshMap296    *ebpf.MapSpec `ebpf:"kmesh_map296"`
	KmeshMap64     *ebpf.MapSpec `ebpf:"kmesh_map64"`
	MapOfHttpProbe *ebpf.MapSpec `ebpf:"map_of_http_probe"`
}

// KmeshTracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTracepointVariableSpecs struct {
	BpfLogLevel *ebpf.VariableSpec `ebpf:"bpf_log_level"`
}

// KmeshTracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTracepointObjects struct {
	KmeshTracepointPrograms
	KmeshTracepointMaps
	KmeshTracepointVariables
}

func (o *KmeshTracepointObjects) Close() error {
	return _KmeshTracepointClose(
		&o.KmeshTracepointPrograms,
		&o.KmeshTracepointMaps,
	)
}

// KmeshTracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTracepointMaps struct {
	KmLogEvent     *ebpf.Map `ebpf:"km_log_event"`
	KmManage       *ebpf.Map `ebpf:"km_manage"`
	KmOrigDst      *ebpf.Map `ebpf:"km_orig_dst"`
	KmPidDst       *ebpf.Map `ebpf:"km_pid_dst"`
	KmSockstorage  *ebpf.Map `ebpf:"km_sockstorage"`
	KmTmpbuf       *ebpf.Map `ebpf:"km_tmpbuf"`
	KmeshMap1600   *ebpf.Map `ebpf:"kmesh_map1600"`
	KmeshMap192    *ebpf.Map `ebpf:"kmesh_map192"`
	KmeshMap296    *ebpf.Map `ebpf:"kmesh_map296"`
	KmeshMap64     *ebpf.Map `ebpf:"kmesh_map64"`
	MapOfHttpProbe *ebpf.Map `ebpf:"map_of_http_probe"`
}

func (m *KmeshTracepointMaps) Close() error {
	return _KmeshTracepointClose(
		m.KmLogEvent,
		m.KmManage,
		m.KmOrigDst,
		m.KmPidDst,
		m.KmSockstorage,
		m.KmTmpbuf,
		m.KmeshMap1600,
		m.KmeshMap192,
		m.KmeshMap296,
		m.KmeshMap64,
		m.MapOfHttpProbe,
	)
}

// KmeshTracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTracepointVariables struct {
	BpfLogLevel *ebpf.Variable `ebpf:"bpf_log_level"`
}

// KmeshTracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTracepointPrograms struct {
	SendmsgEntry *ebpf.Program `ebpf:"sendmsg_entry"`
}

func (p *KmeshTracepointPrograms) Close() error {
	return _KmeshTracepointClose(
		p.SendmsgEntry,
	)
}

func _KmeshTracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kmeshtracepoint_bpfeb.o
var _KmeshTracepointBytes []byte
