// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package dualengine

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type KmeshRecvmsgBpfSockTuple struct {
	Ipv4 struct {
		Saddr uint32
		Daddr uint32
		Sport uint16
		Dport uint16
	}
	_ [24]byte
}

type KmeshRecvmsgBuf struct{ Data [40]int8 }

// LoadKmeshRecvmsg returns the embedded CollectionSpec for KmeshRecvmsg.
func LoadKmeshRecvmsg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KmeshRecvmsgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load KmeshRecvmsg: %w", err)
	}

	return spec, err
}

// LoadKmeshRecvmsgObjects loads KmeshRecvmsg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KmeshRecvmsgObjects
//	*KmeshRecvmsgPrograms
//	*KmeshRecvmsgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKmeshRecvmsgObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKmeshRecvmsg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KmeshRecvmsgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshRecvmsgSpecs struct {
	KmeshRecvmsgProgramSpecs
	KmeshRecvmsgMapSpecs
	KmeshRecvmsgVariableSpecs
}

// KmeshRecvmsgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshRecvmsgProgramSpecs struct {
	RecvmsgProg *ebpf.ProgramSpec `ebpf:"recvmsg_prog"`
}

// KmeshRecvmsgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshRecvmsgMapSpecs struct {
	KmLogEvent *ebpf.MapSpec `ebpf:"km_log_event"`
	KmOrigDst  *ebpf.MapSpec `ebpf:"km_orig_dst"`
	KmTmpbuf   *ebpf.MapSpec `ebpf:"km_tmpbuf"`
}

// KmeshRecvmsgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshRecvmsgVariableSpecs struct {
	BpfLogLevel *ebpf.VariableSpec `ebpf:"bpf_log_level"`
}

// KmeshRecvmsgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshRecvmsgObjects struct {
	KmeshRecvmsgPrograms
	KmeshRecvmsgMaps
	KmeshRecvmsgVariables
}

func (o *KmeshRecvmsgObjects) Close() error {
	return _KmeshRecvmsgClose(
		&o.KmeshRecvmsgPrograms,
		&o.KmeshRecvmsgMaps,
	)
}

// KmeshRecvmsgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshRecvmsgMaps struct {
	KmLogEvent *ebpf.Map `ebpf:"km_log_event"`
	KmOrigDst  *ebpf.Map `ebpf:"km_orig_dst"`
	KmTmpbuf   *ebpf.Map `ebpf:"km_tmpbuf"`
}

func (m *KmeshRecvmsgMaps) Close() error {
	return _KmeshRecvmsgClose(
		m.KmLogEvent,
		m.KmOrigDst,
		m.KmTmpbuf,
	)
}

// KmeshRecvmsgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshRecvmsgVariables struct {
	BpfLogLevel *ebpf.Variable `ebpf:"bpf_log_level"`
}

// KmeshRecvmsgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshRecvmsgPrograms struct {
	RecvmsgProg *ebpf.Program `ebpf:"recvmsg_prog"`
}

func (p *KmeshRecvmsgPrograms) Close() error {
	return _KmeshRecvmsgClose(
		p.RecvmsgProg,
	)
}

func _KmeshRecvmsgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kmeshrecvmsg_bpfel.o
var _KmeshRecvmsgBytes []byte
