// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package dualengine

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type KmeshTcWorkloadCompatBpfSockTuple struct {
	Ipv4 struct {
		Saddr uint32
		Daddr uint32
		Sport uint16
		Dport uint16
	}
	_ [24]byte
}

type KmeshTcWorkloadCompatBuf struct{ Data [40]int8 }

type KmeshTcWorkloadCompatKmeshConfig struct {
	BpfLogLevel      uint32
	NodeIp           [4]uint32
	PodGateway       [4]uint32
	AuthzOffload     uint32
	EnableMonitoring uint32
}

type KmeshTcWorkloadCompatManagerKey struct {
	NetnsCookie uint64
	_           [8]byte
}

type KmeshTcWorkloadCompatOperationUsageData struct {
	StartTime     uint64
	EndTime       uint64
	PidTgid       uint64
	OperationType uint32
	_             [4]byte
}

type KmeshTcWorkloadCompatOperationUsageKey struct {
	SocketCookie  uint64
	OperationType uint32
	_             [4]byte
}

type KmeshTcWorkloadCompatSockStorageData struct {
	ConnectNs      uint64
	Direction      uint8
	ConnectSuccess uint8
	_              [6]byte
	SockCookie     uint64
}

type KmeshTcWorkloadCompatTcpProbeInfo struct {
	Type    uint32
	Tuple   KmeshTcWorkloadCompatBpfSockTuple
	OrigDst struct {
		Ipv4 struct {
			Addr uint32
			Port uint16
			_    [2]byte
		}
		_ [12]byte
	}
	_             [4]byte
	ConnId        uint64
	SentBytes     uint32
	ReceivedBytes uint32
	ConnSuccess   uint32
	Direction     uint32
	State         uint32
	_             [4]byte
	Duration      uint64
	StartNs       uint64
	LastReportNs  uint64
	Protocol      uint32
	SrttUs        uint32
	RttMin        uint32
	TotalRetrans  uint32
	LostOut       uint32
	_             [4]byte
}

// LoadKmeshTcWorkloadCompat returns the embedded CollectionSpec for KmeshTcWorkloadCompat.
func LoadKmeshTcWorkloadCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KmeshTcWorkloadCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load KmeshTcWorkloadCompat: %w", err)
	}

	return spec, err
}

// LoadKmeshTcWorkloadCompatObjects loads KmeshTcWorkloadCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KmeshTcWorkloadCompatObjects
//	*KmeshTcWorkloadCompatPrograms
//	*KmeshTcWorkloadCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKmeshTcWorkloadCompatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKmeshTcWorkloadCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KmeshTcWorkloadCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadCompatSpecs struct {
	KmeshTcWorkloadCompatProgramSpecs
	KmeshTcWorkloadCompatMapSpecs
	KmeshTcWorkloadCompatVariableSpecs
}

// KmeshTcWorkloadCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadCompatProgramSpecs struct {
	TcProg *ebpf.ProgramSpec `ebpf:"tc_prog"`
}

// KmeshTcWorkloadCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadCompatMapSpecs struct {
	KmAuthReq     *ebpf.MapSpec `ebpf:"km_auth_req"`
	KmAuthRes     *ebpf.MapSpec `ebpf:"km_auth_res"`
	KmBackend     *ebpf.MapSpec `ebpf:"km_backend"`
	KmConfigmap   *ebpf.MapSpec `ebpf:"km_configmap"`
	KmConnFlush   *ebpf.MapSpec `ebpf:"km_conn_flush"`
	KmEndpoint    *ebpf.MapSpec `ebpf:"km_endpoint"`
	KmFrontend    *ebpf.MapSpec `ebpf:"km_frontend"`
	KmLogEvent    *ebpf.MapSpec `ebpf:"km_log_event"`
	KmManage      *ebpf.MapSpec `ebpf:"km_manage"`
	KmOrigDst     *ebpf.MapSpec `ebpf:"km_orig_dst"`
	KmPerfInfo    *ebpf.MapSpec `ebpf:"km_perf_info"`
	KmPerfMap     *ebpf.MapSpec `ebpf:"km_perf_map"`
	KmService     *ebpf.MapSpec `ebpf:"km_service"`
	KmSocId       *ebpf.MapSpec `ebpf:"km_soc_id"`
	KmSocIdCnt    *ebpf.MapSpec `ebpf:"km_soc_id_cnt"`
	KmSockstorage *ebpf.MapSpec `ebpf:"km_sockstorage"`
	KmTcpConns    *ebpf.MapSpec `ebpf:"km_tcp_conns"`
	KmTcpProbe    *ebpf.MapSpec `ebpf:"km_tcp_probe"`
	KmTmpbuf      *ebpf.MapSpec `ebpf:"km_tmpbuf"`
	KmWlpolicy    *ebpf.MapSpec `ebpf:"km_wlpolicy"`
	KmeshMap1600  *ebpf.MapSpec `ebpf:"kmesh_map1600"`
	KmeshMap192   *ebpf.MapSpec `ebpf:"kmesh_map192"`
	KmeshMap296   *ebpf.MapSpec `ebpf:"kmesh_map296"`
	KmeshMap64    *ebpf.MapSpec `ebpf:"kmesh_map64"`
}

// KmeshTcWorkloadCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadCompatVariableSpecs struct {
	BpfLogLevel *ebpf.VariableSpec `ebpf:"bpf_log_level"`
}

// KmeshTcWorkloadCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadCompatObjects struct {
	KmeshTcWorkloadCompatPrograms
	KmeshTcWorkloadCompatMaps
	KmeshTcWorkloadCompatVariables
}

func (o *KmeshTcWorkloadCompatObjects) Close() error {
	return _KmeshTcWorkloadCompatClose(
		&o.KmeshTcWorkloadCompatPrograms,
		&o.KmeshTcWorkloadCompatMaps,
	)
}

// KmeshTcWorkloadCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadCompatMaps struct {
	KmAuthReq     *ebpf.Map `ebpf:"km_auth_req"`
	KmAuthRes     *ebpf.Map `ebpf:"km_auth_res"`
	KmBackend     *ebpf.Map `ebpf:"km_backend"`
	KmConfigmap   *ebpf.Map `ebpf:"km_configmap"`
	KmConnFlush   *ebpf.Map `ebpf:"km_conn_flush"`
	KmEndpoint    *ebpf.Map `ebpf:"km_endpoint"`
	KmFrontend    *ebpf.Map `ebpf:"km_frontend"`
	KmLogEvent    *ebpf.Map `ebpf:"km_log_event"`
	KmManage      *ebpf.Map `ebpf:"km_manage"`
	KmOrigDst     *ebpf.Map `ebpf:"km_orig_dst"`
	KmPerfInfo    *ebpf.Map `ebpf:"km_perf_info"`
	KmPerfMap     *ebpf.Map `ebpf:"km_perf_map"`
	KmService     *ebpf.Map `ebpf:"km_service"`
	KmSocId       *ebpf.Map `ebpf:"km_soc_id"`
	KmSocIdCnt    *ebpf.Map `ebpf:"km_soc_id_cnt"`
	KmSockstorage *ebpf.Map `ebpf:"km_sockstorage"`
	KmTcpConns    *ebpf.Map `ebpf:"km_tcp_conns"`
	KmTcpProbe    *ebpf.Map `ebpf:"km_tcp_probe"`
	KmTmpbuf      *ebpf.Map `ebpf:"km_tmpbuf"`
	KmWlpolicy    *ebpf.Map `ebpf:"km_wlpolicy"`
	KmeshMap1600  *ebpf.Map `ebpf:"kmesh_map1600"`
	KmeshMap192   *ebpf.Map `ebpf:"kmesh_map192"`
	KmeshMap296   *ebpf.Map `ebpf:"kmesh_map296"`
	KmeshMap64    *ebpf.Map `ebpf:"kmesh_map64"`
}

func (m *KmeshTcWorkloadCompatMaps) Close() error {
	return _KmeshTcWorkloadCompatClose(
		m.KmAuthReq,
		m.KmAuthRes,
		m.KmBackend,
		m.KmConfigmap,
		m.KmConnFlush,
		m.KmEndpoint,
		m.KmFrontend,
		m.KmLogEvent,
		m.KmManage,
		m.KmOrigDst,
		m.KmPerfInfo,
		m.KmPerfMap,
		m.KmService,
		m.KmSocId,
		m.KmSocIdCnt,
		m.KmSockstorage,
		m.KmTcpConns,
		m.KmTcpProbe,
		m.KmTmpbuf,
		m.KmWlpolicy,
		m.KmeshMap1600,
		m.KmeshMap192,
		m.KmeshMap296,
		m.KmeshMap64,
	)
}

// KmeshTcWorkloadCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadCompatVariables struct {
	BpfLogLevel *ebpf.Variable `ebpf:"bpf_log_level"`
}

// KmeshTcWorkloadCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadCompatPrograms struct {
	TcProg *ebpf.Program `ebpf:"tc_prog"`
}

func (p *KmeshTcWorkloadCompatPrograms) Close() error {
	return _KmeshTcWorkloadCompatClose(
		p.TcProg,
	)
}

func _KmeshTcWorkloadCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kmeshtcworkloadcompat_bpfeb.o
var _KmeshTcWorkloadCompatBytes []byte
