// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package dualengine

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type KmeshTcWorkloadBpfSockTuple struct {
	Ipv4 struct {
		Saddr uint32
		Daddr uint32
		Sport uint16
		Dport uint16
	}
	_ [24]byte
}

type KmeshTcWorkloadBuf struct{ Data [40]int8 }

type KmeshTcWorkloadKmeshConfig struct {
	BpfLogLevel      uint32
	NodeIp           [4]uint32
	PodGateway       [4]uint32
	AuthzOffload     uint32
	EnableMonitoring uint32
}

type KmeshTcWorkloadManagerKey struct {
	NetnsCookie uint64
	_           [8]byte
}

type KmeshTcWorkloadOperationUsageData struct {
	StartTime     uint64
	EndTime       uint64
	PidTgid       uint64
	OperationType uint32
	_             [4]byte
}

type KmeshTcWorkloadOperationUsageKey struct {
	SocketCookie  uint64
	OperationType uint32
	_             [4]byte
}

type KmeshTcWorkloadSockStorageData struct {
	ConnectNs      uint64
	Direction      uint8
	ConnectSuccess uint8
	_              [6]byte
	SockCookie     uint64
}

type KmeshTcWorkloadTcpProbeInfo struct {
	Type    uint32
	Tuple   KmeshTcWorkloadBpfSockTuple
	OrigDst struct {
		Ipv4 struct {
			Addr uint32
			Port uint16
			_    [2]byte
		}
		_ [12]byte
	}
	_             [4]byte
	ConnId        uint64
	SentBytes     uint32
	ReceivedBytes uint32
	ConnSuccess   uint32
	Direction     uint32
	State         uint32
	_             [4]byte
	Duration      uint64
	StartNs       uint64
	LastReportNs  uint64
	Protocol      uint32
	SrttUs        uint32
	RttMin        uint32
	TotalRetrans  uint32
	LostOut       uint32
	_             [4]byte
}

// LoadKmeshTcWorkload returns the embedded CollectionSpec for KmeshTcWorkload.
func LoadKmeshTcWorkload() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KmeshTcWorkloadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load KmeshTcWorkload: %w", err)
	}

	return spec, err
}

// LoadKmeshTcWorkloadObjects loads KmeshTcWorkload and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KmeshTcWorkloadObjects
//	*KmeshTcWorkloadPrograms
//	*KmeshTcWorkloadMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKmeshTcWorkloadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKmeshTcWorkload()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KmeshTcWorkloadSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadSpecs struct {
	KmeshTcWorkloadProgramSpecs
	KmeshTcWorkloadMapSpecs
	KmeshTcWorkloadVariableSpecs
}

// KmeshTcWorkloadProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadProgramSpecs struct {
	TcProg *ebpf.ProgramSpec `ebpf:"tc_prog"`
}

// KmeshTcWorkloadMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadMapSpecs struct {
	KmAuthReq     *ebpf.MapSpec `ebpf:"km_auth_req"`
	KmAuthRes     *ebpf.MapSpec `ebpf:"km_auth_res"`
	KmBackend     *ebpf.MapSpec `ebpf:"km_backend"`
	KmConfigmap   *ebpf.MapSpec `ebpf:"km_configmap"`
	KmConnFlush   *ebpf.MapSpec `ebpf:"km_conn_flush"`
	KmEndpoint    *ebpf.MapSpec `ebpf:"km_endpoint"`
	KmFrontend    *ebpf.MapSpec `ebpf:"km_frontend"`
	KmLogEvent    *ebpf.MapSpec `ebpf:"km_log_event"`
	KmManage      *ebpf.MapSpec `ebpf:"km_manage"`
	KmOrigDst     *ebpf.MapSpec `ebpf:"km_orig_dst"`
	KmPerfInfo    *ebpf.MapSpec `ebpf:"km_perf_info"`
	KmPerfMap     *ebpf.MapSpec `ebpf:"km_perf_map"`
	KmService     *ebpf.MapSpec `ebpf:"km_service"`
	KmSocId       *ebpf.MapSpec `ebpf:"km_soc_id"`
	KmSocIdCnt    *ebpf.MapSpec `ebpf:"km_soc_id_cnt"`
	KmSockstorage *ebpf.MapSpec `ebpf:"km_sockstorage"`
	KmTcpConns    *ebpf.MapSpec `ebpf:"km_tcp_conns"`
	KmTcpProbe    *ebpf.MapSpec `ebpf:"km_tcp_probe"`
	KmTmpbuf      *ebpf.MapSpec `ebpf:"km_tmpbuf"`
	KmWlpolicy    *ebpf.MapSpec `ebpf:"km_wlpolicy"`
	KmeshMap1600  *ebpf.MapSpec `ebpf:"kmesh_map1600"`
	KmeshMap192   *ebpf.MapSpec `ebpf:"kmesh_map192"`
	KmeshMap296   *ebpf.MapSpec `ebpf:"kmesh_map296"`
	KmeshMap64    *ebpf.MapSpec `ebpf:"kmesh_map64"`
}

// KmeshTcWorkloadVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KmeshTcWorkloadVariableSpecs struct {
	BpfLogLevel *ebpf.VariableSpec `ebpf:"bpf_log_level"`
}

// KmeshTcWorkloadObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadObjects struct {
	KmeshTcWorkloadPrograms
	KmeshTcWorkloadMaps
	KmeshTcWorkloadVariables
}

func (o *KmeshTcWorkloadObjects) Close() error {
	return _KmeshTcWorkloadClose(
		&o.KmeshTcWorkloadPrograms,
		&o.KmeshTcWorkloadMaps,
	)
}

// KmeshTcWorkloadMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadMaps struct {
	KmAuthReq     *ebpf.Map `ebpf:"km_auth_req"`
	KmAuthRes     *ebpf.Map `ebpf:"km_auth_res"`
	KmBackend     *ebpf.Map `ebpf:"km_backend"`
	KmConfigmap   *ebpf.Map `ebpf:"km_configmap"`
	KmConnFlush   *ebpf.Map `ebpf:"km_conn_flush"`
	KmEndpoint    *ebpf.Map `ebpf:"km_endpoint"`
	KmFrontend    *ebpf.Map `ebpf:"km_frontend"`
	KmLogEvent    *ebpf.Map `ebpf:"km_log_event"`
	KmManage      *ebpf.Map `ebpf:"km_manage"`
	KmOrigDst     *ebpf.Map `ebpf:"km_orig_dst"`
	KmPerfInfo    *ebpf.Map `ebpf:"km_perf_info"`
	KmPerfMap     *ebpf.Map `ebpf:"km_perf_map"`
	KmService     *ebpf.Map `ebpf:"km_service"`
	KmSocId       *ebpf.Map `ebpf:"km_soc_id"`
	KmSocIdCnt    *ebpf.Map `ebpf:"km_soc_id_cnt"`
	KmSockstorage *ebpf.Map `ebpf:"km_sockstorage"`
	KmTcpConns    *ebpf.Map `ebpf:"km_tcp_conns"`
	KmTcpProbe    *ebpf.Map `ebpf:"km_tcp_probe"`
	KmTmpbuf      *ebpf.Map `ebpf:"km_tmpbuf"`
	KmWlpolicy    *ebpf.Map `ebpf:"km_wlpolicy"`
	KmeshMap1600  *ebpf.Map `ebpf:"kmesh_map1600"`
	KmeshMap192   *ebpf.Map `ebpf:"kmesh_map192"`
	KmeshMap296   *ebpf.Map `ebpf:"kmesh_map296"`
	KmeshMap64    *ebpf.Map `ebpf:"kmesh_map64"`
}

func (m *KmeshTcWorkloadMaps) Close() error {
	return _KmeshTcWorkloadClose(
		m.KmAuthReq,
		m.KmAuthRes,
		m.KmBackend,
		m.KmConfigmap,
		m.KmConnFlush,
		m.KmEndpoint,
		m.KmFrontend,
		m.KmLogEvent,
		m.KmManage,
		m.KmOrigDst,
		m.KmPerfInfo,
		m.KmPerfMap,
		m.KmService,
		m.KmSocId,
		m.KmSocIdCnt,
		m.KmSockstorage,
		m.KmTcpConns,
		m.KmTcpProbe,
		m.KmTmpbuf,
		m.KmWlpolicy,
		m.KmeshMap1600,
		m.KmeshMap192,
		m.KmeshMap296,
		m.KmeshMap64,
	)
}

// KmeshTcWorkloadVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadVariables struct {
	BpfLogLevel *ebpf.Variable `ebpf:"bpf_log_level"`
}

// KmeshTcWorkloadPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKmeshTcWorkloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type KmeshTcWorkloadPrograms struct {
	TcProg *ebpf.Program `ebpf:"tc_prog"`
}

func (p *KmeshTcWorkloadPrograms) Close() error {
	return _KmeshTcWorkloadClose(
		p.TcProg,
	)
}

func _KmeshTcWorkloadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kmeshtcworkload_bpfel.o
var _KmeshTcWorkloadBytes []byte
