/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/admin/config_dump.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "admin/config_dump.pb-c.h"
void   admin__config_dump__init
                     (Admin__ConfigDump         *message)
{
  static const Admin__ConfigDump init_value = ADMIN__CONFIG_DUMP__INIT;
  *message = init_value;
}
size_t admin__config_dump__get_packed_size
                     (const Admin__ConfigDump *message)
{
  assert(message->base.descriptor == &admin__config_dump__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t admin__config_dump__pack
                     (const Admin__ConfigDump *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &admin__config_dump__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t admin__config_dump__pack_to_buffer
                     (const Admin__ConfigDump *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &admin__config_dump__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Admin__ConfigDump *
       admin__config_dump__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Admin__ConfigDump *)
     protobuf_c_message_unpack (&admin__config_dump__descriptor,
                                allocator, len, data);
}
void   admin__config_dump__free_unpacked
                     (Admin__ConfigDump *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &admin__config_dump__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor admin__config_dump__field_descriptors[3] =
{
  {
    "listener_configs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Admin__ConfigDump, n_listener_configs),
    offsetof(Admin__ConfigDump, listener_configs),
    &listener__listener__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route_configs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Admin__ConfigDump, n_route_configs),
    offsetof(Admin__ConfigDump, route_configs),
    &route__route_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cluster_configs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Admin__ConfigDump, n_cluster_configs),
    offsetof(Admin__ConfigDump, cluster_configs),
    &cluster__cluster__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned admin__config_dump__field_indices_by_name[] = {
  2,   /* field[2] = cluster_configs */
  0,   /* field[0] = listener_configs */
  1,   /* field[1] = route_configs */
};
static const ProtobufCIntRange admin__config_dump__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor admin__config_dump__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "admin.ConfigDump",
  "ConfigDump",
  "Admin__ConfigDump",
  "admin",
  sizeof(Admin__ConfigDump),
  3,
  admin__config_dump__field_descriptors,
  admin__config_dump__field_indices_by_name,
  1,  admin__config_dump__number_ranges,
  (ProtobufCMessageInit) admin__config_dump__init,
  NULL,NULL,NULL    /* reserved[123] */
};
