apiVersion: v1
kind: Service
metadata:
  name: httpbin-headless
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  clusterIP: None
  selector:
    app: httpbin