apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kmesh.fullname" . }}
  labels:
    app: kmesh
  {{- include "kmesh.labels" . | nindent 4 }}
  namespace: '{{ .Release.Namespace }}'
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  - nodes
  verbs:
  - get
  - update
  - patch
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kmesh.fullname" . }}
  labels:
    app: kmesh
  {{- include "kmesh.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kmesh.fullname" . }}'
subjects:
- kind: ServiceAccount
  name: '{{ include "kmesh.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
