apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-server-deployment
spec:
  replicas: 40
  selector:
    matchLabels:
      app: fortio-server
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyImage: "istio/proxyv2:1.15.3"
        status.sidecar.istio.io/port: "0"
      labels:
        app: fortio-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: density-node1
      containers:
        - image: fortio/fortio
          imagePullPolicy: IfNotPresent
          name: fortio-server
          ports:
            - containerPort: 8080
              #command: ["fortio", "tcp-echo"]
          resources:
            #limits:
            #cpu: 100m
            #memory: 32Mi
            requests:
              cpu: 100m
              memory: 512Mi


