/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/listener/listener_components.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "listener/listener_components.pb-c.h"
void   listener__filter__init
                     (Listener__Filter         *message)
{
  static const Listener__Filter init_value = LISTENER__FILTER__INIT;
  *message = init_value;
}
size_t listener__filter__get_packed_size
                     (const Listener__Filter *message)
{
  assert(message->base.descriptor == &listener__filter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t listener__filter__pack
                     (const Listener__Filter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &listener__filter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t listener__filter__pack_to_buffer
                     (const Listener__Filter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &listener__filter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Listener__Filter *
       listener__filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Listener__Filter *)
     protobuf_c_message_unpack (&listener__filter__descriptor,
                                allocator, len, data);
}
void   listener__filter__free_unpacked
                     (Listener__Filter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &listener__filter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   listener__filter_chain_match__init
                     (Listener__FilterChainMatch         *message)
{
  static const Listener__FilterChainMatch init_value = LISTENER__FILTER_CHAIN_MATCH__INIT;
  *message = init_value;
}
size_t listener__filter_chain_match__get_packed_size
                     (const Listener__FilterChainMatch *message)
{
  assert(message->base.descriptor == &listener__filter_chain_match__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t listener__filter_chain_match__pack
                     (const Listener__FilterChainMatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &listener__filter_chain_match__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t listener__filter_chain_match__pack_to_buffer
                     (const Listener__FilterChainMatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &listener__filter_chain_match__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Listener__FilterChainMatch *
       listener__filter_chain_match__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Listener__FilterChainMatch *)
     protobuf_c_message_unpack (&listener__filter_chain_match__descriptor,
                                allocator, len, data);
}
void   listener__filter_chain_match__free_unpacked
                     (Listener__FilterChainMatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &listener__filter_chain_match__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   listener__filter_chain__init
                     (Listener__FilterChain         *message)
{
  static const Listener__FilterChain init_value = LISTENER__FILTER_CHAIN__INIT;
  *message = init_value;
}
size_t listener__filter_chain__get_packed_size
                     (const Listener__FilterChain *message)
{
  assert(message->base.descriptor == &listener__filter_chain__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t listener__filter_chain__pack
                     (const Listener__FilterChain *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &listener__filter_chain__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t listener__filter_chain__pack_to_buffer
                     (const Listener__FilterChain *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &listener__filter_chain__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Listener__FilterChain *
       listener__filter_chain__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Listener__FilterChain *)
     protobuf_c_message_unpack (&listener__filter_chain__descriptor,
                                allocator, len, data);
}
void   listener__filter_chain__free_unpacked
                     (Listener__FilterChain *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &listener__filter_chain__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor listener__filter__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Listener__Filter, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_proxy",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Listener__Filter, config_type_case),
    offsetof(Listener__Filter, tcp_proxy),
    &filter__tcp_proxy__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_connection_manager",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Listener__Filter, config_type_case),
    offsetof(Listener__Filter, http_connection_manager),
    &filter__http_connection_manager__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned listener__filter__field_indices_by_name[] = {
  2,   /* field[2] = http_connection_manager */
  0,   /* field[0] = name */
  1,   /* field[1] = tcp_proxy */
};
static const ProtobufCIntRange listener__filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor listener__filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "listener.Filter",
  "Filter",
  "Listener__Filter",
  "listener",
  sizeof(Listener__Filter),
  3,
  listener__filter__field_descriptors,
  listener__filter__field_indices_by_name,
  1,  listener__filter__number_ranges,
  (ProtobufCMessageInit) listener__filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor listener__filter_chain_match__field_descriptors[3] =
{
  {
    "prefix_ranges",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Listener__FilterChainMatch, n_prefix_ranges),
    offsetof(Listener__FilterChainMatch, prefix_ranges),
    &core__cidr_range__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_port",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Listener__FilterChainMatch, destination_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "application_protocols",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Listener__FilterChainMatch, n_application_protocols),
    offsetof(Listener__FilterChainMatch, application_protocols),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned listener__filter_chain_match__field_indices_by_name[] = {
  2,   /* field[2] = application_protocols */
  1,   /* field[1] = destination_port */
  0,   /* field[0] = prefix_ranges */
};
static const ProtobufCIntRange listener__filter_chain_match__number_ranges[3 + 1] =
{
  { 3, 0 },
  { 8, 1 },
  { 10, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor listener__filter_chain_match__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "listener.FilterChainMatch",
  "FilterChainMatch",
  "Listener__FilterChainMatch",
  "listener",
  sizeof(Listener__FilterChainMatch),
  3,
  listener__filter_chain_match__field_descriptors,
  listener__filter_chain_match__field_indices_by_name,
  3,  listener__filter_chain_match__number_ranges,
  (ProtobufCMessageInit) listener__filter_chain_match__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor listener__filter_chain__field_descriptors[3] =
{
  {
    "filter_chain_match",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Listener__FilterChain, filter_chain_match),
    &listener__filter_chain_match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filters",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Listener__FilterChain, n_filters),
    offsetof(Listener__FilterChain, filters),
    &listener__filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Listener__FilterChain, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned listener__filter_chain__field_indices_by_name[] = {
  0,   /* field[0] = filter_chain_match */
  1,   /* field[1] = filters */
  2,   /* field[2] = name */
};
static const ProtobufCIntRange listener__filter_chain__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 7, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor listener__filter_chain__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "listener.FilterChain",
  "FilterChain",
  "Listener__FilterChain",
  "listener",
  sizeof(Listener__FilterChain),
  3,
  listener__filter_chain__field_descriptors,
  listener__filter_chain__field_indices_by_name,
  3,  listener__filter_chain__number_ranges,
  (ProtobufCMessageInit) listener__filter_chain__init,
  NULL,NULL,NULL    /* reserved[123] */
};
