/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/workloadapi/workload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "workloadapi/workload.pb-c.h"
void   workload__address__init
                     (Workload__Address         *message)
{
  static const Workload__Address init_value = WORKLOAD__ADDRESS__INIT;
  *message = init_value;
}
size_t workload__address__get_packed_size
                     (const Workload__Address *message)
{
  assert(message->base.descriptor == &workload__address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__address__pack
                     (const Workload__Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__address__pack_to_buffer
                     (const Workload__Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__Address *
       workload__address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__Address *)
     protobuf_c_message_unpack (&workload__address__descriptor,
                                allocator, len, data);
}
void   workload__address__free_unpacked
                     (Workload__Address *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__service__init
                     (Workload__Service         *message)
{
  static const Workload__Service init_value = WORKLOAD__SERVICE__INIT;
  *message = init_value;
}
size_t workload__service__get_packed_size
                     (const Workload__Service *message)
{
  assert(message->base.descriptor == &workload__service__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__service__pack
                     (const Workload__Service *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__service__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__service__pack_to_buffer
                     (const Workload__Service *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__service__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__Service *
       workload__service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__Service *)
     protobuf_c_message_unpack (&workload__service__descriptor,
                                allocator, len, data);
}
void   workload__service__free_unpacked
                     (Workload__Service *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__service__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__load_balancing__init
                     (Workload__LoadBalancing         *message)
{
  static const Workload__LoadBalancing init_value = WORKLOAD__LOAD_BALANCING__INIT;
  *message = init_value;
}
size_t workload__load_balancing__get_packed_size
                     (const Workload__LoadBalancing *message)
{
  assert(message->base.descriptor == &workload__load_balancing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__load_balancing__pack
                     (const Workload__LoadBalancing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__load_balancing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__load_balancing__pack_to_buffer
                     (const Workload__LoadBalancing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__load_balancing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__LoadBalancing *
       workload__load_balancing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__LoadBalancing *)
     protobuf_c_message_unpack (&workload__load_balancing__descriptor,
                                allocator, len, data);
}
void   workload__load_balancing__free_unpacked
                     (Workload__LoadBalancing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__load_balancing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__workload__services_entry__init
                     (Workload__Workload__ServicesEntry         *message)
{
  static const Workload__Workload__ServicesEntry init_value = WORKLOAD__WORKLOAD__SERVICES_ENTRY__INIT;
  *message = init_value;
}
void   workload__workload__init
                     (Workload__Workload         *message)
{
  static const Workload__Workload init_value = WORKLOAD__WORKLOAD__INIT;
  *message = init_value;
}
size_t workload__workload__get_packed_size
                     (const Workload__Workload *message)
{
  assert(message->base.descriptor == &workload__workload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__workload__pack
                     (const Workload__Workload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__workload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__workload__pack_to_buffer
                     (const Workload__Workload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__workload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__Workload *
       workload__workload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__Workload *)
     protobuf_c_message_unpack (&workload__workload__descriptor,
                                allocator, len, data);
}
void   workload__workload__free_unpacked
                     (Workload__Workload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__workload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__locality__init
                     (Workload__Locality         *message)
{
  static const Workload__Locality init_value = WORKLOAD__LOCALITY__INIT;
  *message = init_value;
}
size_t workload__locality__get_packed_size
                     (const Workload__Locality *message)
{
  assert(message->base.descriptor == &workload__locality__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__locality__pack
                     (const Workload__Locality *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__locality__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__locality__pack_to_buffer
                     (const Workload__Locality *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__locality__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__Locality *
       workload__locality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__Locality *)
     protobuf_c_message_unpack (&workload__locality__descriptor,
                                allocator, len, data);
}
void   workload__locality__free_unpacked
                     (Workload__Locality *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__locality__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__port_list__init
                     (Workload__PortList         *message)
{
  static const Workload__PortList init_value = WORKLOAD__PORT_LIST__INIT;
  *message = init_value;
}
size_t workload__port_list__get_packed_size
                     (const Workload__PortList *message)
{
  assert(message->base.descriptor == &workload__port_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__port_list__pack
                     (const Workload__PortList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__port_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__port_list__pack_to_buffer
                     (const Workload__PortList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__port_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__PortList *
       workload__port_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__PortList *)
     protobuf_c_message_unpack (&workload__port_list__descriptor,
                                allocator, len, data);
}
void   workload__port_list__free_unpacked
                     (Workload__PortList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__port_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__port__init
                     (Workload__Port         *message)
{
  static const Workload__Port init_value = WORKLOAD__PORT__INIT;
  *message = init_value;
}
size_t workload__port__get_packed_size
                     (const Workload__Port *message)
{
  assert(message->base.descriptor == &workload__port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__port__pack
                     (const Workload__Port *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__port__pack_to_buffer
                     (const Workload__Port *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__Port *
       workload__port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__Port *)
     protobuf_c_message_unpack (&workload__port__descriptor,
                                allocator, len, data);
}
void   workload__port__free_unpacked
                     (Workload__Port *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__application_tunnel__init
                     (Workload__ApplicationTunnel         *message)
{
  static const Workload__ApplicationTunnel init_value = WORKLOAD__APPLICATION_TUNNEL__INIT;
  *message = init_value;
}
size_t workload__application_tunnel__get_packed_size
                     (const Workload__ApplicationTunnel *message)
{
  assert(message->base.descriptor == &workload__application_tunnel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__application_tunnel__pack
                     (const Workload__ApplicationTunnel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__application_tunnel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__application_tunnel__pack_to_buffer
                     (const Workload__ApplicationTunnel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__application_tunnel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__ApplicationTunnel *
       workload__application_tunnel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__ApplicationTunnel *)
     protobuf_c_message_unpack (&workload__application_tunnel__descriptor,
                                allocator, len, data);
}
void   workload__application_tunnel__free_unpacked
                     (Workload__ApplicationTunnel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__application_tunnel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__gateway_address__init
                     (Workload__GatewayAddress         *message)
{
  static const Workload__GatewayAddress init_value = WORKLOAD__GATEWAY_ADDRESS__INIT;
  *message = init_value;
}
size_t workload__gateway_address__get_packed_size
                     (const Workload__GatewayAddress *message)
{
  assert(message->base.descriptor == &workload__gateway_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__gateway_address__pack
                     (const Workload__GatewayAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__gateway_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__gateway_address__pack_to_buffer
                     (const Workload__GatewayAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__gateway_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__GatewayAddress *
       workload__gateway_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__GatewayAddress *)
     protobuf_c_message_unpack (&workload__gateway_address__descriptor,
                                allocator, len, data);
}
void   workload__gateway_address__free_unpacked
                     (Workload__GatewayAddress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__gateway_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__network_address__init
                     (Workload__NetworkAddress         *message)
{
  static const Workload__NetworkAddress init_value = WORKLOAD__NETWORK_ADDRESS__INIT;
  *message = init_value;
}
size_t workload__network_address__get_packed_size
                     (const Workload__NetworkAddress *message)
{
  assert(message->base.descriptor == &workload__network_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__network_address__pack
                     (const Workload__NetworkAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__network_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__network_address__pack_to_buffer
                     (const Workload__NetworkAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__network_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__NetworkAddress *
       workload__network_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__NetworkAddress *)
     protobuf_c_message_unpack (&workload__network_address__descriptor,
                                allocator, len, data);
}
void   workload__network_address__free_unpacked
                     (Workload__NetworkAddress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__network_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   workload__namespaced_hostname__init
                     (Workload__NamespacedHostname         *message)
{
  static const Workload__NamespacedHostname init_value = WORKLOAD__NAMESPACED_HOSTNAME__INIT;
  *message = init_value;
}
size_t workload__namespaced_hostname__get_packed_size
                     (const Workload__NamespacedHostname *message)
{
  assert(message->base.descriptor == &workload__namespaced_hostname__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t workload__namespaced_hostname__pack
                     (const Workload__NamespacedHostname *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &workload__namespaced_hostname__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t workload__namespaced_hostname__pack_to_buffer
                     (const Workload__NamespacedHostname *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &workload__namespaced_hostname__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Workload__NamespacedHostname *
       workload__namespaced_hostname__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Workload__NamespacedHostname *)
     protobuf_c_message_unpack (&workload__namespaced_hostname__descriptor,
                                allocator, len, data);
}
void   workload__namespaced_hostname__free_unpacked
                     (Workload__NamespacedHostname *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &workload__namespaced_hostname__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor workload__address__field_descriptors[2] =
{
  {
    "workload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__Address, type_case),
    offsetof(Workload__Address, workload),
    &workload__workload__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__Address, type_case),
    offsetof(Workload__Address, service),
    &workload__service__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__address__field_indices_by_name[] = {
  1,   /* field[1] = service */
  0,   /* field[0] = workload */
};
static const ProtobufCIntRange workload__address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.Address",
  "Address",
  "Workload__Address",
  "workload",
  sizeof(Workload__Address),
  2,
  workload__address__field_descriptors,
  workload__address__field_indices_by_name,
  1,  workload__address__number_ranges,
  (ProtobufCMessageInit) workload__address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__service__field_descriptors[8] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Service, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespace",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Service, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Service, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addresses",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__Service, n_addresses),
    offsetof(Workload__Service, addresses),
    &workload__network_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ports",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__Service, n_ports),
    offsetof(Workload__Service, ports),
    &workload__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject_alt_names",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Workload__Service, n_subject_alt_names),
    offsetof(Workload__Service, subject_alt_names),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "waypoint",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Service, waypoint),
    &workload__gateway_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_balancing",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Service, load_balancing),
    &workload__load_balancing__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__service__field_indices_by_name[] = {
  3,   /* field[3] = addresses */
  2,   /* field[2] = hostname */
  7,   /* field[7] = load_balancing */
  0,   /* field[0] = name */
  1,   /* field[1] = namespace */
  4,   /* field[4] = ports */
  5,   /* field[5] = subject_alt_names */
  6,   /* field[6] = waypoint */
};
static const ProtobufCIntRange workload__service__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor workload__service__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.Service",
  "Service",
  "Workload__Service",
  "workload",
  sizeof(Workload__Service),
  8,
  workload__service__field_descriptors,
  workload__service__field_indices_by_name,
  1,  workload__service__number_ranges,
  (ProtobufCMessageInit) workload__service__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue workload__load_balancing__scope__enum_values_by_number[7] =
{
  { "UNSPECIFIED_SCOPE", "WORKLOAD__LOAD_BALANCING__SCOPE__UNSPECIFIED_SCOPE", 0 },
  { "REGION", "WORKLOAD__LOAD_BALANCING__SCOPE__REGION", 1 },
  { "ZONE", "WORKLOAD__LOAD_BALANCING__SCOPE__ZONE", 2 },
  { "SUBZONE", "WORKLOAD__LOAD_BALANCING__SCOPE__SUBZONE", 3 },
  { "NODE", "WORKLOAD__LOAD_BALANCING__SCOPE__NODE", 4 },
  { "CLUSTER", "WORKLOAD__LOAD_BALANCING__SCOPE__CLUSTER", 5 },
  { "NETWORK", "WORKLOAD__LOAD_BALANCING__SCOPE__NETWORK", 6 },
};
static const ProtobufCIntRange workload__load_balancing__scope__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex workload__load_balancing__scope__enum_values_by_name[7] =
{
  { "CLUSTER", 5 },
  { "NETWORK", 6 },
  { "NODE", 4 },
  { "REGION", 1 },
  { "SUBZONE", 3 },
  { "UNSPECIFIED_SCOPE", 0 },
  { "ZONE", 2 },
};
const ProtobufCEnumDescriptor workload__load_balancing__scope__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "workload.LoadBalancing.Scope",
  "Scope",
  "Workload__LoadBalancing__Scope",
  "workload",
  7,
  workload__load_balancing__scope__enum_values_by_number,
  7,
  workload__load_balancing__scope__enum_values_by_name,
  1,
  workload__load_balancing__scope__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue workload__load_balancing__mode__enum_values_by_number[3] =
{
  { "UNSPECIFIED_MODE", "WORKLOAD__LOAD_BALANCING__MODE__UNSPECIFIED_MODE", 0 },
  { "STRICT", "WORKLOAD__LOAD_BALANCING__MODE__STRICT", 1 },
  { "FAILOVER", "WORKLOAD__LOAD_BALANCING__MODE__FAILOVER", 2 },
};
static const ProtobufCIntRange workload__load_balancing__mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex workload__load_balancing__mode__enum_values_by_name[3] =
{
  { "FAILOVER", 2 },
  { "STRICT", 1 },
  { "UNSPECIFIED_MODE", 0 },
};
const ProtobufCEnumDescriptor workload__load_balancing__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "workload.LoadBalancing.Mode",
  "Mode",
  "Workload__LoadBalancing__Mode",
  "workload",
  3,
  workload__load_balancing__mode__enum_values_by_number,
  3,
  workload__load_balancing__mode__enum_values_by_name,
  1,
  workload__load_balancing__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor workload__load_balancing__field_descriptors[2] =
{
  {
    "routing_preference",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Workload__LoadBalancing, n_routing_preference),
    offsetof(Workload__LoadBalancing, routing_preference),
    &workload__load_balancing__scope__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Workload__LoadBalancing, mode),
    &workload__load_balancing__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__load_balancing__field_indices_by_name[] = {
  1,   /* field[1] = mode */
  0,   /* field[0] = routing_preference */
};
static const ProtobufCIntRange workload__load_balancing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__load_balancing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.LoadBalancing",
  "LoadBalancing",
  "Workload__LoadBalancing",
  "workload",
  sizeof(Workload__LoadBalancing),
  2,
  workload__load_balancing__field_descriptors,
  workload__load_balancing__field_indices_by_name,
  1,  workload__load_balancing__number_ranges,
  (ProtobufCMessageInit) workload__load_balancing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__workload__services_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload__ServicesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload__ServicesEntry, value),
    &workload__port_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__workload__services_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange workload__workload__services_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__workload__services_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.Workload.ServicesEntry",
  "ServicesEntry",
  "Workload__Workload__ServicesEntry",
  "workload",
  sizeof(Workload__Workload__ServicesEntry),
  2,
  workload__workload__services_entry__field_descriptors,
  workload__workload__services_entry__field_indices_by_name,
  1,  workload__workload__services_entry__number_ranges,
  (ProtobufCMessageInit) workload__workload__services_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__workload__field_descriptors[23] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespace",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addresses",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Workload__Workload, n_addresses),
    offsetof(Workload__Workload, addresses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, network),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tunnel_protocol",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, tunnel_protocol),
    &workload__tunnel_protocol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trust_domain",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, trust_domain),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_account",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, service_account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "waypoint",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, waypoint),
    &workload__gateway_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, node),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canonical_name",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, canonical_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canonical_revision",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, canonical_revision),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "workload_type",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, workload_type),
    &workload__workload_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "workload_name",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, workload_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "native_tunnel",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, native_tunnel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authorization_policies",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Workload__Workload, n_authorization_policies),
    offsetof(Workload__Workload, authorization_policies),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, status),
    &workload__workload_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cluster_id",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, cluster_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_gateway",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, network_gateway),
    &workload__gateway_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, uid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__Workload, n_services),
    offsetof(Workload__Workload, services),
    &workload__workload__services_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "application_tunnel",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, application_tunnel),
    &workload__application_tunnel__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locality",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Workload__Workload, locality),
    &workload__locality__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__workload__field_indices_by_name[] = {
  2,   /* field[2] = addresses */
  21,   /* field[21] = application_tunnel */
  14,   /* field[14] = authorization_policies */
  9,   /* field[9] = canonical_name */
  10,   /* field[10] = canonical_revision */
  16,   /* field[16] = cluster_id */
  19,   /* field[19] = hostname */
  22,   /* field[22] = locality */
  0,   /* field[0] = name */
  1,   /* field[1] = namespace */
  13,   /* field[13] = native_tunnel */
  3,   /* field[3] = network */
  17,   /* field[17] = network_gateway */
  8,   /* field[8] = node */
  6,   /* field[6] = service_account */
  20,   /* field[20] = services */
  15,   /* field[15] = status */
  5,   /* field[5] = trust_domain */
  4,   /* field[4] = tunnel_protocol */
  18,   /* field[18] = uid */
  7,   /* field[7] = waypoint */
  12,   /* field[12] = workload_name */
  11,   /* field[11] = workload_type */
};
static const ProtobufCIntRange workload__workload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 16, 14 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor workload__workload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.Workload",
  "Workload",
  "Workload__Workload",
  "workload",
  sizeof(Workload__Workload),
  23,
  workload__workload__field_descriptors,
  workload__workload__field_indices_by_name,
  2,  workload__workload__number_ranges,
  (ProtobufCMessageInit) workload__workload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__locality__field_descriptors[3] =
{
  {
    "region",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Locality, region),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zone",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Locality, zone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subzone",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__Locality, subzone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__locality__field_indices_by_name[] = {
  0,   /* field[0] = region */
  2,   /* field[2] = subzone */
  1,   /* field[1] = zone */
};
static const ProtobufCIntRange workload__locality__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor workload__locality__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.Locality",
  "Locality",
  "Workload__Locality",
  "workload",
  sizeof(Workload__Locality),
  3,
  workload__locality__field_descriptors,
  workload__locality__field_indices_by_name,
  1,  workload__locality__number_ranges,
  (ProtobufCMessageInit) workload__locality__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__port_list__field_descriptors[1] =
{
  {
    "ports",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__PortList, n_ports),
    offsetof(Workload__PortList, ports),
    &workload__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__port_list__field_indices_by_name[] = {
  0,   /* field[0] = ports */
};
static const ProtobufCIntRange workload__port_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor workload__port_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.PortList",
  "PortList",
  "Workload__PortList",
  "workload",
  sizeof(Workload__PortList),
  1,
  workload__port_list__field_descriptors,
  workload__port_list__field_indices_by_name,
  1,  workload__port_list__number_ranges,
  (ProtobufCMessageInit) workload__port_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__port__field_descriptors[2] =
{
  {
    "service_port",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Workload__Port, service_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Workload__Port, target_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__port__field_indices_by_name[] = {
  0,   /* field[0] = service_port */
  1,   /* field[1] = target_port */
};
static const ProtobufCIntRange workload__port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__port__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.Port",
  "Port",
  "Workload__Port",
  "workload",
  sizeof(Workload__Port),
  2,
  workload__port__field_descriptors,
  workload__port__field_indices_by_name,
  1,  workload__port__number_ranges,
  (ProtobufCMessageInit) workload__port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue workload__application_tunnel__protocol__enum_values_by_number[2] =
{
  { "NONE", "WORKLOAD__APPLICATION_TUNNEL__PROTOCOL__NONE", 0 },
  { "PROXY", "WORKLOAD__APPLICATION_TUNNEL__PROTOCOL__PROXY", 1 },
};
static const ProtobufCIntRange workload__application_tunnel__protocol__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex workload__application_tunnel__protocol__enum_values_by_name[2] =
{
  { "NONE", 0 },
  { "PROXY", 1 },
};
const ProtobufCEnumDescriptor workload__application_tunnel__protocol__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "workload.ApplicationTunnel.Protocol",
  "Protocol",
  "Workload__ApplicationTunnel__Protocol",
  "workload",
  2,
  workload__application_tunnel__protocol__enum_values_by_number,
  2,
  workload__application_tunnel__protocol__enum_values_by_name,
  1,
  workload__application_tunnel__protocol__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor workload__application_tunnel__field_descriptors[2] =
{
  {
    "protocol",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Workload__ApplicationTunnel, protocol),
    &workload__application_tunnel__protocol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Workload__ApplicationTunnel, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__application_tunnel__field_indices_by_name[] = {
  1,   /* field[1] = port */
  0,   /* field[0] = protocol */
};
static const ProtobufCIntRange workload__application_tunnel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__application_tunnel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.ApplicationTunnel",
  "ApplicationTunnel",
  "Workload__ApplicationTunnel",
  "workload",
  sizeof(Workload__ApplicationTunnel),
  2,
  workload__application_tunnel__field_descriptors,
  workload__application_tunnel__field_indices_by_name,
  1,  workload__application_tunnel__number_ranges,
  (ProtobufCMessageInit) workload__application_tunnel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__gateway_address__field_descriptors[4] =
{
  {
    "hostname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__GatewayAddress, destination_case),
    offsetof(Workload__GatewayAddress, hostname),
    &workload__namespaced_hostname__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Workload__GatewayAddress, destination_case),
    offsetof(Workload__GatewayAddress, address),
    &workload__network_address__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hbone_mtls_port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Workload__GatewayAddress, hbone_mtls_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hbone_single_tls_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Workload__GatewayAddress, hbone_single_tls_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__gateway_address__field_indices_by_name[] = {
  1,   /* field[1] = address */
  2,   /* field[2] = hbone_mtls_port */
  3,   /* field[3] = hbone_single_tls_port */
  0,   /* field[0] = hostname */
};
static const ProtobufCIntRange workload__gateway_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor workload__gateway_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.GatewayAddress",
  "GatewayAddress",
  "Workload__GatewayAddress",
  "workload",
  sizeof(Workload__GatewayAddress),
  4,
  workload__gateway_address__field_descriptors,
  workload__gateway_address__field_indices_by_name,
  1,  workload__gateway_address__number_ranges,
  (ProtobufCMessageInit) workload__gateway_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__network_address__field_descriptors[2] =
{
  {
    "network",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__NetworkAddress, network),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Workload__NetworkAddress, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__network_address__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = network */
};
static const ProtobufCIntRange workload__network_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__network_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.NetworkAddress",
  "NetworkAddress",
  "Workload__NetworkAddress",
  "workload",
  sizeof(Workload__NetworkAddress),
  2,
  workload__network_address__field_descriptors,
  workload__network_address__field_indices_by_name,
  1,  workload__network_address__number_ranges,
  (ProtobufCMessageInit) workload__network_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor workload__namespaced_hostname__field_descriptors[2] =
{
  {
    "namespace",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__NamespacedHostname, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Workload__NamespacedHostname, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned workload__namespaced_hostname__field_indices_by_name[] = {
  1,   /* field[1] = hostname */
  0,   /* field[0] = namespace */
};
static const ProtobufCIntRange workload__namespaced_hostname__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor workload__namespaced_hostname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "workload.NamespacedHostname",
  "NamespacedHostname",
  "Workload__NamespacedHostname",
  "workload",
  sizeof(Workload__NamespacedHostname),
  2,
  workload__namespaced_hostname__field_descriptors,
  workload__namespaced_hostname__field_indices_by_name,
  1,  workload__namespaced_hostname__number_ranges,
  (ProtobufCMessageInit) workload__namespaced_hostname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue workload__workload_status__enum_values_by_number[2] =
{
  { "HEALTHY", "WORKLOAD__WORKLOAD_STATUS__HEALTHY", 0 },
  { "UNHEALTHY", "WORKLOAD__WORKLOAD_STATUS__UNHEALTHY", 1 },
};
static const ProtobufCIntRange workload__workload_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex workload__workload_status__enum_values_by_name[2] =
{
  { "HEALTHY", 0 },
  { "UNHEALTHY", 1 },
};
const ProtobufCEnumDescriptor workload__workload_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "workload.WorkloadStatus",
  "WorkloadStatus",
  "Workload__WorkloadStatus",
  "workload",
  2,
  workload__workload_status__enum_values_by_number,
  2,
  workload__workload_status__enum_values_by_name,
  1,
  workload__workload_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue workload__workload_type__enum_values_by_number[4] =
{
  { "DEPLOYMENT", "WORKLOAD__WORKLOAD_TYPE__DEPLOYMENT", 0 },
  { "CRONJOB", "WORKLOAD__WORKLOAD_TYPE__CRONJOB", 1 },
  { "POD", "WORKLOAD__WORKLOAD_TYPE__POD", 2 },
  { "JOB", "WORKLOAD__WORKLOAD_TYPE__JOB", 3 },
};
static const ProtobufCIntRange workload__workload_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex workload__workload_type__enum_values_by_name[4] =
{
  { "CRONJOB", 1 },
  { "DEPLOYMENT", 0 },
  { "JOB", 3 },
  { "POD", 2 },
};
const ProtobufCEnumDescriptor workload__workload_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "workload.WorkloadType",
  "WorkloadType",
  "Workload__WorkloadType",
  "workload",
  4,
  workload__workload_type__enum_values_by_number,
  4,
  workload__workload_type__enum_values_by_name,
  1,
  workload__workload_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue workload__tunnel_protocol__enum_values_by_number[2] =
{
  { "NONE", "WORKLOAD__TUNNEL_PROTOCOL__NONE", 0 },
  { "HBONE", "WORKLOAD__TUNNEL_PROTOCOL__HBONE", 1 },
};
static const ProtobufCIntRange workload__tunnel_protocol__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex workload__tunnel_protocol__enum_values_by_name[2] =
{
  { "HBONE", 1 },
  { "NONE", 0 },
};
const ProtobufCEnumDescriptor workload__tunnel_protocol__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "workload.TunnelProtocol",
  "TunnelProtocol",
  "Workload__TunnelProtocol",
  "workload",
  2,
  workload__tunnel_protocol__enum_values_by_number,
  2,
  workload__tunnel_protocol__enum_values_by_name,
  1,
  workload__tunnel_protocol__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
