/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/workloadapi/workload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "workloadapi/workload.pb-c.h"
void   istio__workload__address__init
                     (Istio__Workload__Address         *message)
{
  static const Istio__Workload__Address init_value = ISTIO__WORKLOAD__ADDRESS__INIT;
  *message = init_value;
}
size_t istio__workload__address__get_packed_size
                     (const Istio__Workload__Address *message)
{
  assert(message->base.descriptor == &istio__workload__address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__address__pack
                     (const Istio__Workload__Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__address__pack_to_buffer
                     (const Istio__Workload__Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__Address *
       istio__workload__address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__Address *)
     protobuf_c_message_unpack (&istio__workload__address__descriptor,
                                allocator, len, data);
}
void   istio__workload__address__free_unpacked
                     (Istio__Workload__Address *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__service__init
                     (Istio__Workload__Service         *message)
{
  static const Istio__Workload__Service init_value = ISTIO__WORKLOAD__SERVICE__INIT;
  *message = init_value;
}
size_t istio__workload__service__get_packed_size
                     (const Istio__Workload__Service *message)
{
  assert(message->base.descriptor == &istio__workload__service__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__service__pack
                     (const Istio__Workload__Service *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__service__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__service__pack_to_buffer
                     (const Istio__Workload__Service *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__service__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__Service *
       istio__workload__service__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__Service *)
     protobuf_c_message_unpack (&istio__workload__service__descriptor,
                                allocator, len, data);
}
void   istio__workload__service__free_unpacked
                     (Istio__Workload__Service *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__service__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__workload__services_entry__init
                     (Istio__Workload__Workload__ServicesEntry         *message)
{
  static const Istio__Workload__Workload__ServicesEntry init_value = ISTIO__WORKLOAD__WORKLOAD__SERVICES_ENTRY__INIT;
  *message = init_value;
}
void   istio__workload__workload__init
                     (Istio__Workload__Workload         *message)
{
  static const Istio__Workload__Workload init_value = ISTIO__WORKLOAD__WORKLOAD__INIT;
  *message = init_value;
}
size_t istio__workload__workload__get_packed_size
                     (const Istio__Workload__Workload *message)
{
  assert(message->base.descriptor == &istio__workload__workload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__workload__pack
                     (const Istio__Workload__Workload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__workload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__workload__pack_to_buffer
                     (const Istio__Workload__Workload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__workload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__Workload *
       istio__workload__workload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__Workload *)
     protobuf_c_message_unpack (&istio__workload__workload__descriptor,
                                allocator, len, data);
}
void   istio__workload__workload__free_unpacked
                     (Istio__Workload__Workload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__workload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__port_list__init
                     (Istio__Workload__PortList         *message)
{
  static const Istio__Workload__PortList init_value = ISTIO__WORKLOAD__PORT_LIST__INIT;
  *message = init_value;
}
size_t istio__workload__port_list__get_packed_size
                     (const Istio__Workload__PortList *message)
{
  assert(message->base.descriptor == &istio__workload__port_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__port_list__pack
                     (const Istio__Workload__PortList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__port_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__port_list__pack_to_buffer
                     (const Istio__Workload__PortList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__port_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__PortList *
       istio__workload__port_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__PortList *)
     protobuf_c_message_unpack (&istio__workload__port_list__descriptor,
                                allocator, len, data);
}
void   istio__workload__port_list__free_unpacked
                     (Istio__Workload__PortList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__port_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__port__init
                     (Istio__Workload__Port         *message)
{
  static const Istio__Workload__Port init_value = ISTIO__WORKLOAD__PORT__INIT;
  *message = init_value;
}
size_t istio__workload__port__get_packed_size
                     (const Istio__Workload__Port *message)
{
  assert(message->base.descriptor == &istio__workload__port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__port__pack
                     (const Istio__Workload__Port *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__port__pack_to_buffer
                     (const Istio__Workload__Port *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__Port *
       istio__workload__port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__Port *)
     protobuf_c_message_unpack (&istio__workload__port__descriptor,
                                allocator, len, data);
}
void   istio__workload__port__free_unpacked
                     (Istio__Workload__Port *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__gateway_address__init
                     (Istio__Workload__GatewayAddress         *message)
{
  static const Istio__Workload__GatewayAddress init_value = ISTIO__WORKLOAD__GATEWAY_ADDRESS__INIT;
  *message = init_value;
}
size_t istio__workload__gateway_address__get_packed_size
                     (const Istio__Workload__GatewayAddress *message)
{
  assert(message->base.descriptor == &istio__workload__gateway_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__gateway_address__pack
                     (const Istio__Workload__GatewayAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__gateway_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__gateway_address__pack_to_buffer
                     (const Istio__Workload__GatewayAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__gateway_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__GatewayAddress *
       istio__workload__gateway_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__GatewayAddress *)
     protobuf_c_message_unpack (&istio__workload__gateway_address__descriptor,
                                allocator, len, data);
}
void   istio__workload__gateway_address__free_unpacked
                     (Istio__Workload__GatewayAddress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__gateway_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__network_address__init
                     (Istio__Workload__NetworkAddress         *message)
{
  static const Istio__Workload__NetworkAddress init_value = ISTIO__WORKLOAD__NETWORK_ADDRESS__INIT;
  *message = init_value;
}
size_t istio__workload__network_address__get_packed_size
                     (const Istio__Workload__NetworkAddress *message)
{
  assert(message->base.descriptor == &istio__workload__network_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__network_address__pack
                     (const Istio__Workload__NetworkAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__network_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__network_address__pack_to_buffer
                     (const Istio__Workload__NetworkAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__network_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__NetworkAddress *
       istio__workload__network_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__NetworkAddress *)
     protobuf_c_message_unpack (&istio__workload__network_address__descriptor,
                                allocator, len, data);
}
void   istio__workload__network_address__free_unpacked
                     (Istio__Workload__NetworkAddress *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__network_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   istio__workload__namespaced_hostname__init
                     (Istio__Workload__NamespacedHostname         *message)
{
  static const Istio__Workload__NamespacedHostname init_value = ISTIO__WORKLOAD__NAMESPACED_HOSTNAME__INIT;
  *message = init_value;
}
size_t istio__workload__namespaced_hostname__get_packed_size
                     (const Istio__Workload__NamespacedHostname *message)
{
  assert(message->base.descriptor == &istio__workload__namespaced_hostname__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t istio__workload__namespaced_hostname__pack
                     (const Istio__Workload__NamespacedHostname *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &istio__workload__namespaced_hostname__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t istio__workload__namespaced_hostname__pack_to_buffer
                     (const Istio__Workload__NamespacedHostname *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &istio__workload__namespaced_hostname__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Istio__Workload__NamespacedHostname *
       istio__workload__namespaced_hostname__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Istio__Workload__NamespacedHostname *)
     protobuf_c_message_unpack (&istio__workload__namespaced_hostname__descriptor,
                                allocator, len, data);
}
void   istio__workload__namespaced_hostname__free_unpacked
                     (Istio__Workload__NamespacedHostname *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &istio__workload__namespaced_hostname__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor istio__workload__address__field_descriptors[2] =
{
  {
    "workload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__Address, type_case),
    offsetof(Istio__Workload__Address, workload),
    &istio__workload__workload__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__Address, type_case),
    offsetof(Istio__Workload__Address, service),
    &istio__workload__service__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__address__field_indices_by_name[] = {
  1,   /* field[1] = service */
  0,   /* field[0] = workload */
};
static const ProtobufCIntRange istio__workload__address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor istio__workload__address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.Address",
  "Address",
  "Istio__Workload__Address",
  "istio.workload",
  sizeof(Istio__Workload__Address),
  2,
  istio__workload__address__field_descriptors,
  istio__workload__address__field_indices_by_name,
  1,  istio__workload__address__number_ranges,
  (ProtobufCMessageInit) istio__workload__address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__service__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Service, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespace",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Service, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Service, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addresses",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__Service, n_addresses),
    offsetof(Istio__Workload__Service, addresses),
    &istio__workload__network_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ports",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__Service, n_ports),
    offsetof(Istio__Workload__Service, ports),
    &istio__workload__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subject_alt_names",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Istio__Workload__Service, n_subject_alt_names),
    offsetof(Istio__Workload__Service, subject_alt_names),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__service__field_indices_by_name[] = {
  3,   /* field[3] = addresses */
  2,   /* field[2] = hostname */
  0,   /* field[0] = name */
  1,   /* field[1] = namespace */
  4,   /* field[4] = ports */
  5,   /* field[5] = subject_alt_names */
};
static const ProtobufCIntRange istio__workload__service__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor istio__workload__service__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.Service",
  "Service",
  "Istio__Workload__Service",
  "istio.workload",
  sizeof(Istio__Workload__Service),
  6,
  istio__workload__service__field_descriptors,
  istio__workload__service__field_indices_by_name,
  1,  istio__workload__service__number_ranges,
  (ProtobufCMessageInit) istio__workload__service__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__workload__services_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload__ServicesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload__ServicesEntry, value),
    &istio__workload__port_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__workload__services_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange istio__workload__workload__services_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor istio__workload__workload__services_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.Workload.ServicesEntry",
  "ServicesEntry",
  "Istio__Workload__Workload__ServicesEntry",
  "istio.workload",
  sizeof(Istio__Workload__Workload__ServicesEntry),
  2,
  istio__workload__workload__services_entry__field_descriptors,
  istio__workload__workload__services_entry__field_indices_by_name,
  1,  istio__workload__workload__services_entry__number_ranges,
  (ProtobufCMessageInit) istio__workload__workload__services_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__workload__field_descriptors[21] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespace",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addresses",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Istio__Workload__Workload, n_addresses),
    offsetof(Istio__Workload__Workload, addresses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, network),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tunnel_protocol",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, tunnel_protocol),
    &istio__workload__tunnel_protocol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trust_domain",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, trust_domain),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_account",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, service_account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "waypoint",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, waypoint),
    &istio__workload__gateway_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, node),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canonical_name",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, canonical_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canonical_revision",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, canonical_revision),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "workload_type",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, workload_type),
    &istio__workload__workload_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "workload_name",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, workload_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "native_tunnel",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, native_tunnel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authorization_policies",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Istio__Workload__Workload, n_authorization_policies),
    offsetof(Istio__Workload__Workload, authorization_policies),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, status),
    &istio__workload__workload_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cluster_id",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, cluster_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_gateway",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, network_gateway),
    &istio__workload__gateway_address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, uid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Workload, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "services",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__Workload, n_services),
    offsetof(Istio__Workload__Workload, services),
    &istio__workload__workload__services_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__workload__field_indices_by_name[] = {
  2,   /* field[2] = addresses */
  14,   /* field[14] = authorization_policies */
  9,   /* field[9] = canonical_name */
  10,   /* field[10] = canonical_revision */
  16,   /* field[16] = cluster_id */
  19,   /* field[19] = hostname */
  0,   /* field[0] = name */
  1,   /* field[1] = namespace */
  13,   /* field[13] = native_tunnel */
  3,   /* field[3] = network */
  17,   /* field[17] = network_gateway */
  8,   /* field[8] = node */
  6,   /* field[6] = service_account */
  20,   /* field[20] = services */
  15,   /* field[15] = status */
  5,   /* field[5] = trust_domain */
  4,   /* field[4] = tunnel_protocol */
  18,   /* field[18] = uid */
  7,   /* field[7] = waypoint */
  12,   /* field[12] = workload_name */
  11,   /* field[11] = workload_type */
};
static const ProtobufCIntRange istio__workload__workload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 16, 14 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor istio__workload__workload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.Workload",
  "Workload",
  "Istio__Workload__Workload",
  "istio.workload",
  sizeof(Istio__Workload__Workload),
  21,
  istio__workload__workload__field_descriptors,
  istio__workload__workload__field_indices_by_name,
  2,  istio__workload__workload__number_ranges,
  (ProtobufCMessageInit) istio__workload__workload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__port_list__field_descriptors[1] =
{
  {
    "ports",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__PortList, n_ports),
    offsetof(Istio__Workload__PortList, ports),
    &istio__workload__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__port_list__field_indices_by_name[] = {
  0,   /* field[0] = ports */
};
static const ProtobufCIntRange istio__workload__port_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor istio__workload__port_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.PortList",
  "PortList",
  "Istio__Workload__PortList",
  "istio.workload",
  sizeof(Istio__Workload__PortList),
  1,
  istio__workload__port_list__field_descriptors,
  istio__workload__port_list__field_indices_by_name,
  1,  istio__workload__port_list__number_ranges,
  (ProtobufCMessageInit) istio__workload__port_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__port__field_descriptors[2] =
{
  {
    "service_port",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Port, service_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__Port, target_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__port__field_indices_by_name[] = {
  0,   /* field[0] = service_port */
  1,   /* field[1] = target_port */
};
static const ProtobufCIntRange istio__workload__port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor istio__workload__port__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.Port",
  "Port",
  "Istio__Workload__Port",
  "istio.workload",
  sizeof(Istio__Workload__Port),
  2,
  istio__workload__port__field_descriptors,
  istio__workload__port__field_indices_by_name,
  1,  istio__workload__port__number_ranges,
  (ProtobufCMessageInit) istio__workload__port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__gateway_address__field_descriptors[4] =
{
  {
    "hostname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__GatewayAddress, destination_case),
    offsetof(Istio__Workload__GatewayAddress, hostname),
    &istio__workload__namespaced_hostname__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Istio__Workload__GatewayAddress, destination_case),
    offsetof(Istio__Workload__GatewayAddress, address),
    &istio__workload__network_address__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hbone_mtls_port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__GatewayAddress, hbone_mtls_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hbone_single_tls_port",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__GatewayAddress, hbone_single_tls_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__gateway_address__field_indices_by_name[] = {
  1,   /* field[1] = address */
  2,   /* field[2] = hbone_mtls_port */
  3,   /* field[3] = hbone_single_tls_port */
  0,   /* field[0] = hostname */
};
static const ProtobufCIntRange istio__workload__gateway_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor istio__workload__gateway_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.GatewayAddress",
  "GatewayAddress",
  "Istio__Workload__GatewayAddress",
  "istio.workload",
  sizeof(Istio__Workload__GatewayAddress),
  4,
  istio__workload__gateway_address__field_descriptors,
  istio__workload__gateway_address__field_indices_by_name,
  1,  istio__workload__gateway_address__number_ranges,
  (ProtobufCMessageInit) istio__workload__gateway_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__network_address__field_descriptors[2] =
{
  {
    "network",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__NetworkAddress, network),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__NetworkAddress, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__network_address__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = network */
};
static const ProtobufCIntRange istio__workload__network_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor istio__workload__network_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.NetworkAddress",
  "NetworkAddress",
  "Istio__Workload__NetworkAddress",
  "istio.workload",
  sizeof(Istio__Workload__NetworkAddress),
  2,
  istio__workload__network_address__field_descriptors,
  istio__workload__network_address__field_indices_by_name,
  1,  istio__workload__network_address__number_ranges,
  (ProtobufCMessageInit) istio__workload__network_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor istio__workload__namespaced_hostname__field_descriptors[2] =
{
  {
    "namespace",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__NamespacedHostname, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Istio__Workload__NamespacedHostname, hostname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned istio__workload__namespaced_hostname__field_indices_by_name[] = {
  1,   /* field[1] = hostname */
  0,   /* field[0] = namespace */
};
static const ProtobufCIntRange istio__workload__namespaced_hostname__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor istio__workload__namespaced_hostname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "istio.workload.NamespacedHostname",
  "NamespacedHostname",
  "Istio__Workload__NamespacedHostname",
  "istio.workload",
  sizeof(Istio__Workload__NamespacedHostname),
  2,
  istio__workload__namespaced_hostname__field_descriptors,
  istio__workload__namespaced_hostname__field_indices_by_name,
  1,  istio__workload__namespaced_hostname__number_ranges,
  (ProtobufCMessageInit) istio__workload__namespaced_hostname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue istio__workload__workload_status__enum_values_by_number[2] =
{
  { "HEALTHY", "ISTIO__WORKLOAD__WORKLOAD_STATUS__HEALTHY", 0 },
  { "UNHEALTHY", "ISTIO__WORKLOAD__WORKLOAD_STATUS__UNHEALTHY", 1 },
};
static const ProtobufCIntRange istio__workload__workload_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex istio__workload__workload_status__enum_values_by_name[2] =
{
  { "HEALTHY", 0 },
  { "UNHEALTHY", 1 },
};
const ProtobufCEnumDescriptor istio__workload__workload_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "istio.workload.WorkloadStatus",
  "WorkloadStatus",
  "Istio__Workload__WorkloadStatus",
  "istio.workload",
  2,
  istio__workload__workload_status__enum_values_by_number,
  2,
  istio__workload__workload_status__enum_values_by_name,
  1,
  istio__workload__workload_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue istio__workload__workload_type__enum_values_by_number[4] =
{
  { "DEPLOYMENT", "ISTIO__WORKLOAD__WORKLOAD_TYPE__DEPLOYMENT", 0 },
  { "CRONJOB", "ISTIO__WORKLOAD__WORKLOAD_TYPE__CRONJOB", 1 },
  { "POD", "ISTIO__WORKLOAD__WORKLOAD_TYPE__POD", 2 },
  { "JOB", "ISTIO__WORKLOAD__WORKLOAD_TYPE__JOB", 3 },
};
static const ProtobufCIntRange istio__workload__workload_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex istio__workload__workload_type__enum_values_by_name[4] =
{
  { "CRONJOB", 1 },
  { "DEPLOYMENT", 0 },
  { "JOB", 3 },
  { "POD", 2 },
};
const ProtobufCEnumDescriptor istio__workload__workload_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "istio.workload.WorkloadType",
  "WorkloadType",
  "Istio__Workload__WorkloadType",
  "istio.workload",
  4,
  istio__workload__workload_type__enum_values_by_number,
  4,
  istio__workload__workload_type__enum_values_by_name,
  1,
  istio__workload__workload_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue istio__workload__tunnel_protocol__enum_values_by_number[2] =
{
  { "NONE", "ISTIO__WORKLOAD__TUNNEL_PROTOCOL__NONE", 0 },
  { "HBONE", "ISTIO__WORKLOAD__TUNNEL_PROTOCOL__HBONE", 1 },
};
static const ProtobufCIntRange istio__workload__tunnel_protocol__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex istio__workload__tunnel_protocol__enum_values_by_name[2] =
{
  { "HBONE", 1 },
  { "NONE", 0 },
};
const ProtobufCEnumDescriptor istio__workload__tunnel_protocol__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "istio.workload.TunnelProtocol",
  "TunnelProtocol",
  "Istio__Workload__TunnelProtocol",
  "istio.workload",
  2,
  istio__workload__tunnel_protocol__enum_values_by_number,
  2,
  istio__workload__tunnel_protocol__enum_values_by_name,
  1,
  istio__workload__tunnel_protocol__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
