/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/core/base.proto */

#ifndef PROTOBUF_C_api_2fcore_2fbase_2eproto__INCLUDED
#define PROTOBUF_C_api_2fcore_2fbase_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

/*
 * The status of the control-plane of the current data is identified to
 * determine the corresponding lower control-plane operation.
 */
typedef enum _Core__ApiStatus {
  CORE__API_STATUS__NONE = 0,
  CORE__API_STATUS__DELETE = 1,
  CORE__API_STATUS__UPDATE = 2,
  CORE__API_STATUS__UNCHANGED = 3,
  CORE__API_STATUS__ALL = 4,
  /*
   * Waiting for associated endpoints before updating bpf map
   * Currently only apply to cluster resource.
   */
  CORE__API_STATUS__WAITING = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CORE__API_STATUS)
} Core__ApiStatus;
typedef enum _Core__RoutingPriority {
  CORE__ROUTING_PRIORITY__DEFAULT = 0,
  CORE__ROUTING_PRIORITY__HIGH = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CORE__ROUTING_PRIORITY)
} Core__RoutingPriority;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    core__api_status__descriptor;
extern const ProtobufCEnumDescriptor    core__routing_priority__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_api_2fcore_2fbase_2eproto__INCLUDED */
