/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/filter/tcp_proxy.proto */

#ifndef PROTOBUF_C_api_2ffilter_2ftcp_5fproxy_2eproto__INCLUDED
#define PROTOBUF_C_api_2ffilter_2ftcp_5fproxy_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Filter__TcpProxy Filter__TcpProxy;


/* --- enums --- */


/* --- messages --- */

struct  _Filter__TcpProxy
{
  ProtobufCMessage base;
  char *cluster;
};
#define FILTER__TCP_PROXY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&filter__tcp_proxy__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Filter__TcpProxy methods */
void   filter__tcp_proxy__init
                     (Filter__TcpProxy         *message);
size_t filter__tcp_proxy__get_packed_size
                     (const Filter__TcpProxy   *message);
size_t filter__tcp_proxy__pack
                     (const Filter__TcpProxy   *message,
                      uint8_t             *out);
size_t filter__tcp_proxy__pack_to_buffer
                     (const Filter__TcpProxy   *message,
                      ProtobufCBuffer     *buffer);
Filter__TcpProxy *
       filter__tcp_proxy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   filter__tcp_proxy__free_unpacked
                     (Filter__TcpProxy *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Filter__TcpProxy_Closure)
                 (const Filter__TcpProxy *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor filter__tcp_proxy__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_api_2ffilter_2ftcp_5fproxy_2eproto__INCLUDED */
