apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service1
  name: nginx-service1
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service2
  name: nginx-service2
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service3
  name: nginx-service3
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service4
  name: nginx-service4
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service5
  name: nginx-service5
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service6
  name: nginx-service6
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service6
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service7
  name: nginx-service7
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service7
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service8
  name: nginx-service8
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-service8
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortio-server-nginx
  name: fortio-server-nginx
  namespace: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fortio-server-nginx
