apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fortio-server-nginx-ingress"
  namespace: nginx
spec:
  endpointSelector:
    matchLabels:
      app: fortio-server-nginx
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: nginx-service1
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/"
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "nginx-service1-egress"
  namespace: nginx
spec:
  endpointSelector:
    matchLabels:
      app: nginx-service1
  egress:
  - toEndpoints:
    - matchLabels:
        app: fortio-server-nginx
    toPorts:
      - ports:
        - port: "8080"
          protocol: TCP
        rules:
          http:
          - method: "GET"
            path: "/"