name: Chinese Grammar Check

on:
  push:
    paths:
      - 'docs/**'
      - 'docs/proposal/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'docs/proposal/**'

jobs:
  grammar-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install language-tool-python python-docx markdown

      - name: Run grammar check
        run: python chinese_grammar_checker.py

      - name: Upload grammar check report
        uses: actions/upload-artifact@v4
        with:
          name: grammar-report
          path: grammar_report.txt
