/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/route/route_components.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "route/route_components.pb-c.h"
void   route__virtual_host__init
                     (Route__VirtualHost         *message)
{
  static const Route__VirtualHost init_value = ROUTE__VIRTUAL_HOST__INIT;
  *message = init_value;
}
size_t route__virtual_host__get_packed_size
                     (const Route__VirtualHost *message)
{
  assert(message->base.descriptor == &route__virtual_host__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__virtual_host__pack
                     (const Route__VirtualHost *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &route__virtual_host__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__virtual_host__pack_to_buffer
                     (const Route__VirtualHost *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &route__virtual_host__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route__VirtualHost *
       route__virtual_host__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route__VirtualHost *)
     protobuf_c_message_unpack (&route__virtual_host__descriptor,
                                allocator, len, data);
}
void   route__virtual_host__free_unpacked
                     (Route__VirtualHost *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &route__virtual_host__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   route__route__init
                     (Route__Route         *message)
{
  static const Route__Route init_value = ROUTE__ROUTE__INIT;
  *message = init_value;
}
size_t route__route__get_packed_size
                     (const Route__Route *message)
{
  assert(message->base.descriptor == &route__route__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__route__pack
                     (const Route__Route *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &route__route__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__route__pack_to_buffer
                     (const Route__Route *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &route__route__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route__Route *
       route__route__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route__Route *)
     protobuf_c_message_unpack (&route__route__descriptor,
                                allocator, len, data);
}
void   route__route__free_unpacked
                     (Route__Route *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &route__route__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   route__route_match__init
                     (Route__RouteMatch         *message)
{
  static const Route__RouteMatch init_value = ROUTE__ROUTE_MATCH__INIT;
  *message = init_value;
}
size_t route__route_match__get_packed_size
                     (const Route__RouteMatch *message)
{
  assert(message->base.descriptor == &route__route_match__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__route_match__pack
                     (const Route__RouteMatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &route__route_match__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__route_match__pack_to_buffer
                     (const Route__RouteMatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &route__route_match__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route__RouteMatch *
       route__route_match__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route__RouteMatch *)
     protobuf_c_message_unpack (&route__route_match__descriptor,
                                allocator, len, data);
}
void   route__route_match__free_unpacked
                     (Route__RouteMatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &route__route_match__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   route__route_action__init
                     (Route__RouteAction         *message)
{
  static const Route__RouteAction init_value = ROUTE__ROUTE_ACTION__INIT;
  *message = init_value;
}
size_t route__route_action__get_packed_size
                     (const Route__RouteAction *message)
{
  assert(message->base.descriptor == &route__route_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__route_action__pack
                     (const Route__RouteAction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &route__route_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__route_action__pack_to_buffer
                     (const Route__RouteAction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &route__route_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route__RouteAction *
       route__route_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route__RouteAction *)
     protobuf_c_message_unpack (&route__route_action__descriptor,
                                allocator, len, data);
}
void   route__route_action__free_unpacked
                     (Route__RouteAction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &route__route_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   route__retry_policy__init
                     (Route__RetryPolicy         *message)
{
  static const Route__RetryPolicy init_value = ROUTE__RETRY_POLICY__INIT;
  *message = init_value;
}
size_t route__retry_policy__get_packed_size
                     (const Route__RetryPolicy *message)
{
  assert(message->base.descriptor == &route__retry_policy__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__retry_policy__pack
                     (const Route__RetryPolicy *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &route__retry_policy__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__retry_policy__pack_to_buffer
                     (const Route__RetryPolicy *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &route__retry_policy__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route__RetryPolicy *
       route__retry_policy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route__RetryPolicy *)
     protobuf_c_message_unpack (&route__retry_policy__descriptor,
                                allocator, len, data);
}
void   route__retry_policy__free_unpacked
                     (Route__RetryPolicy *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &route__retry_policy__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor route__virtual_host__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Route__VirtualHost, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "domains",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Route__VirtualHost, n_domains),
    offsetof(Route__VirtualHost, domains),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "routes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Route__VirtualHost, n_routes),
    offsetof(Route__VirtualHost, routes),
    &route__route__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned route__virtual_host__field_indices_by_name[] = {
  1,   /* field[1] = domains */
  0,   /* field[0] = name */
  2,   /* field[2] = routes */
};
static const ProtobufCIntRange route__virtual_host__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor route__virtual_host__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "route.VirtualHost",
  "VirtualHost",
  "Route__VirtualHost",
  "route",
  sizeof(Route__VirtualHost),
  3,
  route__virtual_host__field_descriptors,
  route__virtual_host__field_indices_by_name,
  1,  route__virtual_host__number_ranges,
  (ProtobufCMessageInit) route__virtual_host__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor route__route__field_descriptors[3] =
{
  {
    "match",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Route__Route, match),
    &route__route_match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Route__Route, route),
    &route__route_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Route__Route, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned route__route__field_indices_by_name[] = {
  0,   /* field[0] = match */
  2,   /* field[2] = name */
  1,   /* field[1] = route */
};
static const ProtobufCIntRange route__route__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor route__route__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "route.Route",
  "Route",
  "Route__Route",
  "route",
  sizeof(Route__Route),
  3,
  route__route__field_descriptors,
  route__route__field_indices_by_name,
  2,  route__route__number_ranges,
  (ProtobufCMessageInit) route__route__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor route__route_match__field_descriptors[1] =
{
  {
    "prefix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Route__RouteMatch, prefix),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned route__route_match__field_indices_by_name[] = {
  0,   /* field[0] = prefix */
};
static const ProtobufCIntRange route__route_match__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor route__route_match__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "route.RouteMatch",
  "RouteMatch",
  "Route__RouteMatch",
  "route",
  sizeof(Route__RouteMatch),
  1,
  route__route_match__field_descriptors,
  route__route_match__field_indices_by_name,
  1,  route__route_match__number_ranges,
  (ProtobufCMessageInit) route__route_match__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor route__route_action__field_descriptors[3] =
{
  {
    "cluster",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Route__RouteAction, cluster),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Route__RouteAction, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retry_policy",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Route__RouteAction, retry_policy),
    &route__retry_policy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned route__route_action__field_indices_by_name[] = {
  0,   /* field[0] = cluster */
  2,   /* field[2] = retry_policy */
  1,   /* field[1] = timeout */
};
static const ProtobufCIntRange route__route_action__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor route__route_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "route.RouteAction",
  "RouteAction",
  "Route__RouteAction",
  "route",
  sizeof(Route__RouteAction),
  3,
  route__route_action__field_descriptors,
  route__route_action__field_indices_by_name,
  2,  route__route_action__number_ranges,
  (ProtobufCMessageInit) route__route_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor route__retry_policy__field_descriptors[1] =
{
  {
    "num_retries",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Route__RetryPolicy, num_retries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned route__retry_policy__field_indices_by_name[] = {
  0,   /* field[0] = num_retries */
};
static const ProtobufCIntRange route__retry_policy__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor route__retry_policy__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "route.RetryPolicy",
  "RetryPolicy",
  "Route__RetryPolicy",
  "route",
  sizeof(Route__RetryPolicy),
  1,
  route__retry_policy__field_descriptors,
  route__retry_policy__field_indices_by_name,
  1,  route__retry_policy__number_ranges,
  (ProtobufCMessageInit) route__retry_policy__init,
  NULL,NULL,NULL    /* reserved[123] */
};
