/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api/workloadapi/security/authorization.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "workloadapi/security/authorization.pb-c.h"
void   security__authorization__init
                     (Security__Authorization         *message)
{
  static const Security__Authorization init_value = SECURITY__AUTHORIZATION__INIT;
  *message = init_value;
}
size_t security__authorization__get_packed_size
                     (const Security__Authorization *message)
{
  assert(message->base.descriptor == &security__authorization__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t security__authorization__pack
                     (const Security__Authorization *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &security__authorization__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t security__authorization__pack_to_buffer
                     (const Security__Authorization *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &security__authorization__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Security__Authorization *
       security__authorization__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Security__Authorization *)
     protobuf_c_message_unpack (&security__authorization__descriptor,
                                allocator, len, data);
}
void   security__authorization__free_unpacked
                     (Security__Authorization *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &security__authorization__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   security__rule__init
                     (Security__Rule         *message)
{
  static const Security__Rule init_value = SECURITY__RULE__INIT;
  *message = init_value;
}
size_t security__rule__get_packed_size
                     (const Security__Rule *message)
{
  assert(message->base.descriptor == &security__rule__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t security__rule__pack
                     (const Security__Rule *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &security__rule__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t security__rule__pack_to_buffer
                     (const Security__Rule *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &security__rule__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Security__Rule *
       security__rule__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Security__Rule *)
     protobuf_c_message_unpack (&security__rule__descriptor,
                                allocator, len, data);
}
void   security__rule__free_unpacked
                     (Security__Rule *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &security__rule__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   security__clause__init
                     (Security__Clause         *message)
{
  static const Security__Clause init_value = SECURITY__CLAUSE__INIT;
  *message = init_value;
}
size_t security__clause__get_packed_size
                     (const Security__Clause *message)
{
  assert(message->base.descriptor == &security__clause__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t security__clause__pack
                     (const Security__Clause *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &security__clause__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t security__clause__pack_to_buffer
                     (const Security__Clause *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &security__clause__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Security__Clause *
       security__clause__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Security__Clause *)
     protobuf_c_message_unpack (&security__clause__descriptor,
                                allocator, len, data);
}
void   security__clause__free_unpacked
                     (Security__Clause *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &security__clause__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   security__match__init
                     (Security__Match         *message)
{
  static const Security__Match init_value = SECURITY__MATCH__INIT;
  *message = init_value;
}
size_t security__match__get_packed_size
                     (const Security__Match *message)
{
  assert(message->base.descriptor == &security__match__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t security__match__pack
                     (const Security__Match *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &security__match__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t security__match__pack_to_buffer
                     (const Security__Match *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &security__match__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Security__Match *
       security__match__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Security__Match *)
     protobuf_c_message_unpack (&security__match__descriptor,
                                allocator, len, data);
}
void   security__match__free_unpacked
                     (Security__Match *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &security__match__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   security__address__init
                     (Security__Address         *message)
{
  static const Security__Address init_value = SECURITY__ADDRESS__INIT;
  *message = init_value;
}
size_t security__address__get_packed_size
                     (const Security__Address *message)
{
  assert(message->base.descriptor == &security__address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t security__address__pack
                     (const Security__Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &security__address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t security__address__pack_to_buffer
                     (const Security__Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &security__address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Security__Address *
       security__address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Security__Address *)
     protobuf_c_message_unpack (&security__address__descriptor,
                                allocator, len, data);
}
void   security__address__free_unpacked
                     (Security__Address *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &security__address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   security__string_match__init
                     (Security__StringMatch         *message)
{
  static const Security__StringMatch init_value = SECURITY__STRING_MATCH__INIT;
  *message = init_value;
}
size_t security__string_match__get_packed_size
                     (const Security__StringMatch *message)
{
  assert(message->base.descriptor == &security__string_match__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t security__string_match__pack
                     (const Security__StringMatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &security__string_match__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t security__string_match__pack_to_buffer
                     (const Security__StringMatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &security__string_match__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Security__StringMatch *
       security__string_match__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Security__StringMatch *)
     protobuf_c_message_unpack (&security__string_match__descriptor,
                                allocator, len, data);
}
void   security__string_match__free_unpacked
                     (Security__StringMatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &security__string_match__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor security__authorization__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Security__Authorization, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespace",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Security__Authorization, namespace_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scope",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Security__Authorization, scope),
    &security__scope__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Security__Authorization, action),
    &security__action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rules",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Authorization, n_rules),
    offsetof(Security__Authorization, rules),
    &security__rule__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned security__authorization__field_indices_by_name[] = {
  3,   /* field[3] = action */
  0,   /* field[0] = name */
  1,   /* field[1] = namespace */
  4,   /* field[4] = rules */
  2,   /* field[2] = scope */
};
static const ProtobufCIntRange security__authorization__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor security__authorization__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "security.Authorization",
  "Authorization",
  "Security__Authorization",
  "security",
  sizeof(Security__Authorization),
  5,
  security__authorization__field_descriptors,
  security__authorization__field_indices_by_name,
  1,  security__authorization__number_ranges,
  (ProtobufCMessageInit) security__authorization__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor security__rule__field_descriptors[1] =
{
  {
    "clauses",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Rule, n_clauses),
    offsetof(Security__Rule, clauses),
    &security__clause__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned security__rule__field_indices_by_name[] = {
  0,   /* field[0] = clauses */
};
static const ProtobufCIntRange security__rule__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor security__rule__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "security.Rule",
  "Rule",
  "Security__Rule",
  "security",
  sizeof(Security__Rule),
  1,
  security__rule__field_descriptors,
  security__rule__field_indices_by_name,
  1,  security__rule__number_ranges,
  (ProtobufCMessageInit) security__rule__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor security__clause__field_descriptors[1] =
{
  {
    "matches",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Clause, n_matches),
    offsetof(Security__Clause, matches),
    &security__match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned security__clause__field_indices_by_name[] = {
  0,   /* field[0] = matches */
};
static const ProtobufCIntRange security__clause__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor security__clause__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "security.Clause",
  "Clause",
  "Security__Clause",
  "security",
  sizeof(Security__Clause),
  1,
  security__clause__field_descriptors,
  security__clause__field_indices_by_name,
  1,  security__clause__number_ranges,
  (ProtobufCMessageInit) security__clause__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor security__match__field_descriptors[10] =
{
  {
    "namespaces",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_namespaces),
    offsetof(Security__Match, namespaces),
    &security__string_match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_namespaces",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_not_namespaces),
    offsetof(Security__Match, not_namespaces),
    &security__string_match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "principals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_principals),
    offsetof(Security__Match, principals),
    &security__string_match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_principals",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_not_principals),
    offsetof(Security__Match, not_principals),
    &security__string_match__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_ips",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_source_ips),
    offsetof(Security__Match, source_ips),
    &security__address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_source_ips",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_not_source_ips),
    offsetof(Security__Match, not_source_ips),
    &security__address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_ips",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_destination_ips),
    offsetof(Security__Match, destination_ips),
    &security__address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_destination_ips",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Security__Match, n_not_destination_ips),
    offsetof(Security__Match, not_destination_ips),
    &security__address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_ports",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Security__Match, n_destination_ports),
    offsetof(Security__Match, destination_ports),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_destination_ports",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Security__Match, n_not_destination_ports),
    offsetof(Security__Match, not_destination_ports),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned security__match__field_indices_by_name[] = {
  6,   /* field[6] = destination_ips */
  8,   /* field[8] = destination_ports */
  0,   /* field[0] = namespaces */
  7,   /* field[7] = not_destination_ips */
  9,   /* field[9] = not_destination_ports */
  1,   /* field[1] = not_namespaces */
  3,   /* field[3] = not_principals */
  5,   /* field[5] = not_source_ips */
  2,   /* field[2] = principals */
  4,   /* field[4] = source_ips */
};
static const ProtobufCIntRange security__match__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor security__match__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "security.Match",
  "Match",
  "Security__Match",
  "security",
  sizeof(Security__Match),
  10,
  security__match__field_descriptors,
  security__match__field_indices_by_name,
  1,  security__match__number_ranges,
  (ProtobufCMessageInit) security__match__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor security__address__field_descriptors[2] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Security__Address, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Security__Address, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned security__address__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange security__address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor security__address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "security.Address",
  "Address",
  "Security__Address",
  "security",
  sizeof(Security__Address),
  2,
  security__address__field_descriptors,
  security__address__field_indices_by_name,
  1,  security__address__number_ranges,
  (ProtobufCMessageInit) security__address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor security__string_match__field_descriptors[3] =
{
  {
    "exact",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Security__StringMatch, match_type_case),
    offsetof(Security__StringMatch, exact),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prefix",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Security__StringMatch, match_type_case),
    offsetof(Security__StringMatch, prefix),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suffix",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Security__StringMatch, match_type_case),
    offsetof(Security__StringMatch, suffix),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned security__string_match__field_indices_by_name[] = {
  0,   /* field[0] = exact */
  1,   /* field[1] = prefix */
  2,   /* field[2] = suffix */
};
static const ProtobufCIntRange security__string_match__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor security__string_match__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "security.StringMatch",
  "StringMatch",
  "Security__StringMatch",
  "security",
  sizeof(Security__StringMatch),
  3,
  security__string_match__field_descriptors,
  security__string_match__field_indices_by_name,
  1,  security__string_match__number_ranges,
  (ProtobufCMessageInit) security__string_match__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue security__scope__enum_values_by_number[3] =
{
  { "GLOBAL", "SECURITY__SCOPE__GLOBAL", 0 },
  { "NAMESPACE", "SECURITY__SCOPE__NAMESPACE", 1 },
  { "WORKLOAD_SELECTOR", "SECURITY__SCOPE__WORKLOAD_SELECTOR", 2 },
};
static const ProtobufCIntRange security__scope__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex security__scope__enum_values_by_name[3] =
{
  { "GLOBAL", 0 },
  { "NAMESPACE", 1 },
  { "WORKLOAD_SELECTOR", 2 },
};
const ProtobufCEnumDescriptor security__scope__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "security.Scope",
  "Scope",
  "Security__Scope",
  "security",
  3,
  security__scope__enum_values_by_number,
  3,
  security__scope__enum_values_by_name,
  1,
  security__scope__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue security__action__enum_values_by_number[2] =
{
  { "ALLOW", "SECURITY__ACTION__ALLOW", 0 },
  { "DENY", "SECURITY__ACTION__DENY", 1 },
};
static const ProtobufCIntRange security__action__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex security__action__enum_values_by_name[2] =
{
  { "ALLOW", 0 },
  { "DENY", 1 },
};
const ProtobufCEnumDescriptor security__action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "security.Action",
  "Action",
  "Security__Action",
  "security",
  2,
  security__action__enum_values_by_number,
  2,
  security__action__enum_values_by_name,
  1,
  security__action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
