name: E2E IPv6 Test(istio 1.25)
on: 
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.png'
jobs:  
  e2e-ipv6-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: [ '1.23' ]
    name: E2E IPv6 Test
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: E2E IPv6 Test
      shell: bash
      run: |
        sudo ISTIO_VERSION="1.25.1" make e2e-ipv6