name: E2E Test(istio 1.24)
on: 
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.png'
jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: [ '1.23' ]
    name: E2E Test
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: E2E Test
      shell: bash
      run: |
        sudo ISTIO_VERSION="1.24.0" make e2e