name: BPF Compatability Test on Kernel 5.15

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.png'
  merge_group: # enable merge queue
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ '1.23' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Prepare kernel header # because the kernel header is up to date with 5.15
        shell: bash
        run: |
          sudo cp /usr/src/linux-headers-$(uname -r)/include/uapi/linux/bpf.h /usr/include/linux/bpf.h

      - name: Go Test
        run: |
          sudo make test RUN_IN_CONTAINER=1

      - name: eBPF Unit Test
        run: |
          sudo make ebpf_unit_test RUN_IN_CONTAINER=1 V=1
