name: Lint Workflow

on:
  pull_request:
    paths-ignore:
      - "**.svg"
      - "**.png"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: ["1.23"]

    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md,!docs/ctl"
          separator: ","
